### ISSUE TITLE
less files under lib/assets/stylesheets wasn't found

### ISSUE THREAD

**Issue by Saranya-Raaj** [davidwkeith/middleman-multisite-example#1]
I have added some less fils under lib/assets/stylesheets (say _layout.less)  and imported the same in source/mypro/stylesheets/index.css.less file (like @import "_layout.less"; ).
However, when I run the build task, I am getting the following error : 

.rvm/gems/ruby-1.9.3-p385/gems/less-2.3.2/lib/less/js/lib/less/parser.js:434:69): '_layout.less' wasn't found. (Less::ParseError)

Why does my import statement in the index.css.less file not working. Please help me out.

**Comment by davidwkeith** [comment]
Ok, I added the config I use for Compass/Sass on 0ada22a

I have not used Less, but I would imagine a similar solution is possible.
